# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import bqs_lease_pb2 as bqs__lease__pb2

GRPC_GENERATED_VERSION = '1.75.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in bqs_lease_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class NodeManagerStub(object):
    """The NodeManager service provides RPC methods for managing node leases.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLease = channel.unary_unary(
                '/NodeManager/GetLease',
                request_serializer=bqs__lease__pb2.LeaseRequest.SerializeToString,
                response_deserializer=bqs__lease__pb2.Lease.FromString,
                _registered_method=True)
        self.RenewLease = channel.unary_unary(
                '/NodeManager/RenewLease',
                request_serializer=bqs__lease__pb2.LeaseRequest.SerializeToString,
                response_deserializer=bqs__lease__pb2.Lease.FromString,
                _registered_method=True)
        self.ReleaseLease = channel.unary_unary(
                '/NodeManager/ReleaseLease',
                request_serializer=bqs__lease__pb2.Lease.SerializeToString,
                response_deserializer=bqs__lease__pb2.Lease.FromString,
                _registered_method=True)


class NodeManagerServicer(object):
    """The NodeManager service provides RPC methods for managing node leases.
    """

    def GetLease(self, request, context):
        """Generates a lease based on the provided LeaseRequest.
        Parameters:
        LeaseRequest: The request containing criteria for the lease.
        Returns:
        Lease: The lease details corresponding to the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RenewLease(self, request, context):
        """Renews a lease based on the provided LeaseRequest.
        Parameters:
        LeaseRequest: The request containing the callsign and nodeId for the lease.
        Returns:
        Lease: The renewed lease details corresponding to the request.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseLease(self, request, context):
        """Releases a previously acquired lease on a node.
        Parameters:
        LeaseRequest: The request containing the callsign and nodeId for the lease.
        Returns:
        Lease: A void lease containing the nodeId and a default expiry
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_NodeManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLease': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLease,
                    request_deserializer=bqs__lease__pb2.LeaseRequest.FromString,
                    response_serializer=bqs__lease__pb2.Lease.SerializeToString,
            ),
            'RenewLease': grpc.unary_unary_rpc_method_handler(
                    servicer.RenewLease,
                    request_deserializer=bqs__lease__pb2.LeaseRequest.FromString,
                    response_serializer=bqs__lease__pb2.Lease.SerializeToString,
            ),
            'ReleaseLease': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseLease,
                    request_deserializer=bqs__lease__pb2.Lease.FromString,
                    response_serializer=bqs__lease__pb2.Lease.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'NodeManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('NodeManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class NodeManager(object):
    """The NodeManager service provides RPC methods for managing node leases.
    """

    @staticmethod
    def GetLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NodeManager/GetLease',
            bqs__lease__pb2.LeaseRequest.SerializeToString,
            bqs__lease__pb2.Lease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RenewLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NodeManager/RenewLease',
            bqs__lease__pb2.LeaseRequest.SerializeToString,
            bqs__lease__pb2.Lease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseLease(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/NodeManager/ReleaseLease',
            bqs__lease__pb2.Lease.SerializeToString,
            bqs__lease__pb2.Lease.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
